/*
///////////////////////////////////////////////
      _      _____ _____ ______ _______ _____ 
     / \    / ____/ ____|  ____|__   __/ ____|
    / . \  | (___| (___ | |__     | | | (___  
   / /_\ \  \___ \\___ \|  __|    | |  \___ \ 
  / _____ \ ____) |___) | |____   | |  ____) |
 /_/     \_\_____/_____/|______|  |_| |_____/ 
///////////////////////////////////////////////
///////////////////////////////////////////////
- Alter the values here to adjust the information
	displayed. When adding new data, refer to the
	templates provided to ensure consistency.

*/
const loadingQuotes = [
  "I didn't want to be a woman; I've always been a woman.",
  "Learn to celebrate and place value on your uniqueness.",
  "I am beautiful and I deserve love.",
  "I am the architect of my life; I build its foundation and choose its contents.",
  "Today, I am brimming with energy and overflowing with joy.",
  "My body is healthy; my mind is brilliant; my soul is tranquil.",
  "I am superior to negative thoughts and low actions.",
  "I have been given endless talents which I begin to utilize today.",
  "I forgive those who have harmed me in my past and peacefully detach from them.",
  "A river of compassion washes away my anger and replaces it with love.",
  "I am guided in my every step by Spirit who leads me towards what I must know and do.",
  "I possess the qualities needed to be extremely successful.",
  "Creative energy surges through me and leads me to new and brilliant ideas.",
  "Happiness is a choice. I base my happiness on my own accomplishments and the blessings I’ve been given.",
  "My ability to conquer my challenges is limitless; my potential to succeed is infinite.",
  "I am courageous and I stand up for myself.",
  "My thoughts are filled with positivity and my life is plentiful with prosperity.",
  "Today, I abandon my old habits and take up new, more positive ones.",
  "Many people look up to me and recognize my worth; I am admired.",
  "I am blessed with an incredible family and wonderful friends.",
  "I acknowledge my own self-worth; my confidence is soaring.",
  "Everything that is happening now is happening for my ultimate good.",
  "Champions keep playing until they get it right.",
  "I am a powerhouse; I am indestructible.",
  "Though these times are difficult, they are only a short phase of life.",
  "My future is an ideal projection of what I envision now.",
  "My efforts are being supported by the universe; my dreams manifest into reality before my eyes.",
  "I radiate beauty, charm, and grace.",
  "My obstacles are moving out of my way; my path is carved towards greatness.",
  "I wake up today with strength in my heart and clarity in my mind.",
  "My fears of tomorrow are simply melting away.",
  "I am at peace with all that has happened, is happening, and will happen.",
  "My nature is Divine; I am a spiritual being.",
  "My life is just beginning.",
  "I deserve health, happiness, and love.",
  "Transition into your best life!",
  "You are beautifully created.",
  "When I dare to be powerful, to use my strength in the service of my vision, then it becomes less and less important whether I am afraid.",
  "If everything was perfect, you would never learn and you would never grow.",
  "We all have our imperfections. But I’m human, and you know, it’s important to concentrate on other qualities besides outer beauty.",
  "If you can’t love yourself how in the hell can you love somebody else.",
  "Try to be a rainbow in someone’s cloud.",
  "If you can love me, you can love yourself",
  "By doing the work to love ourselves more, I believe we will love each other better.",
  "I make a difference in the world by simply existing in it.",
  "I am infinitely resourceful.",
  "I am everything I need.",
  "Failure is an opportunity for growth.",
  "My beauty is not about how I look. My beauty is about my heart and soul.",
  "My boundaries deserve respect.",
  "I am comfortable asking for what I want because I know I deserve it.",
  "I am an expert on myself. I know who I am and what I need.",
  "I get to name my body parts however I want.",
  "My gender is not up for debate by others.",
  "My pronouns are not complicated.",
  "Remember, goals are stars to steer by, not sticks with which to beat ourselves.",
  "Steel is not forged in a comfortable place.",
  "I identify as what I am.",
  "I am transgender and this doesn't mean that I am unlovable.",
  "My future is an ideal projection of what I envision now.",
  "Simplicity is nice.",
  "If you cannot do great things, do small things in a great way.",
  "I'd rather regret the things I've done than regret the things I haven't done.",
  "I didn't get there by wishing for it or hoping for it, but by working for it.",
  "Perseverance is failing 19 times and succeeding the 20th.",
  "I consider how my decisions affect others to be responsible.",
  "I breathe in calmness and breathe out nervousness.",
  "I am loving and lovable.",
  "My body vibrates with energy and health.",
  "I love everything about my body.",
  "I appreciate my body's unique traits.",
  "I crave new, healthy experiences.",
  "My work has a profound impact on the world.",
  "I choose to participate fully in my day.",
  "I always find ways to get back on track.",
  "I am in control of my life.",
  "I attract success.",
  "I make a conscious choice to be happy.",
  "I let go of worries that drain my energy.",
  "My intuition leads me to abundance.",
  "Everywhere I look, I see abundance.",
  "Today, I will do my absolute best.",
  "I express gratitude for the blessings that I receive.",
  "I will speak kindly to and of others.",
  "I will set aside time to be silent and breathe.",
  "I have the power to control my reactions to the challenges I face.",
  "Love rules my thoughts and actions.",
  "I am free from fearful thoughts.",
  "My thoughts are filled with peace and tranquility.",
  "I am willing to forgive.",
  "I release myself from my anger and let the past go.",
  "Today, I forgive myself.",
  "I accept the good that is flowing into my life.",
  "Happiness and more happiness is mine.",
  "Happy thoughts bring happy things.",
  "I release my thoughts and meditate with ease.",
  "I am willing to be successful.",
  "I release the things that are not my responsibility to control.",
  "I approve of myself.",
  "I light the world with my smile.",
  "My presence makes a difference in the world.",
  "My message is clear and well received.",
  "I speak with clarity and power.",
  "I am a powerful body, a powerful mind, and a powerful soul.",
  "I am peaceful.",
  "I calmly process the events of the day.",
  "I am proud of myself.",
  "I love me.",
  "I am a phenomenal woman.",
  "Today is filled with opportunity.",
  "I am grateful for today.",
  "Today I will be pleasantly surprised.",
  "I am surrounded by the love of friends.",
  "I am open to all forms of treatment for mind, body, and soul.",
  "I choose to take good care of myself.",
  "I have the potential to heal completely.",
  "Health is the foundation of my being.",
  "I am so grateful for my healing.",
  "I will accomplish the goals I set for myself.",
  "The path toward my goal is clear.",
  "I honor my mission and values by pursuing my goals.",
  "My hard work is paying off.",
  "I attract friends easily.",
  "I am thankful for my friends.",
  "My friends allow me the freedom to be who I truly am.",
  "I choose to be at peace with the way that things are.",
  "I am patient with my painful emotions.",
  "I choose to have the strength to move on.",
  "I allow my mind to be at rest with the decision that has been made.",
  "I am compassionate with myself and my heart.",
  "I have the potential to experience love greater than I have ever known.",
  "I am whole, complete, and perfect just as I am.",
  "My life is filled with possibility.",
  "I choose to be successful in each area of my life.",
  "I know that I am capable of the impossible.",
  "I have a keen capacity to learn new skills that support my success.",
  "I release all blocks pertaining to my goal.",
  "I effortlessly reach my goals.",
  "I allow peace to fill my mind.",
  "Love continues forever.",
  "I am willing to step out of my comfort zone.",
  "I choose to express a confident attitude to others.",
  "I choose to be proud of myself.",
  "The only way to achieve is to trust yourself.",
  "Push yourself because nobody will do it for you.",
  "They key to success is to focus on the goal, not the obstacles.",
  "Just breathe, trust, and let go. See where life will take you.",
  "Doing the best at this moment puts you in the best place for the next moment.",
  "When you do things from your soul, you feel a river moving in you, a joy.",
  "The most courageous act is still… to think for yourself. Aloud.",
  "Shatter the grip of fear and anxiety.",
  "Doubt kills more dreams than failure ever will.",
  "Talent is cheaper than table salt. What separates the talented individual from the successful one is a lot of hard work.",
  "Courage is the most important of all the virtues, because without courage, you can't practice any other virtue consistently.",
  "Set your life on fire. Seek those who fan your flames.",
  "The past, the present, and the future are really one: they are today.",
  "If I wait for someone else to validate my existence, it will mean that I'm shortchanging myself.",
  "The most effective way to do it, is to do it.",
  "Don't ever be afraid to show off your true colors.",
  "I feel the love of those who are not physically around me.",
  "I love and approve of myself.",
  "I trust myself.",
  "I draw from my inner strength and light.",
  "I am a unique child of this world.",
  "I have as much brightness to offer the world as the next person.",
  "I matter and what I have to offer this world also matters.",
  "Wonderful things unfold before me.",
  "I offer an apology to those affected by my anger.",
  "I muster up more hope and courage from deep inside me.",
  "I kindly ask for help and guidance if I cannot see a better way.",
  "I refuse to give up because I haven't tried all possible ways.",
  "I know my wisdom guides me to the right decision.",
  "I love my family even if they do not understand me completely.",
  "I receive all feedback with kindness but make the final call myself.",
  "I show love in all the verbal and non-verbal ways I can.",
  "I take great pleasure in my friends, even if we disagree or live different lives.",
  "I am beautiful and smart and that's how everyone sees me.",
  "I never know what amazing incredible person I will meet next.",
  "The company of strangers teaches me more about my own likes and dislikes.",
  "Peaceful sleep awaits me in dreamland.",
  "I let go of all the false stories I make up in my head.",
  "This day brings me nothing but joy.",
  "Today will be a gorgeous day to remember.",
  "I make smart, calculated plans for my future.",
  "I am in complete charge of planning for my future.",
  "I accept everyone as they are and continue on with pursuing my dream.",
  "I seek a new way of thinking about this situation.",
  "The answer is right before me, even if I am not seeing it yet.",
  "I believe in my ability to unlock the way and set myself free.",
  "I have no right to compare myself to anyone for I do not know their whole story.",
  "I compare myself only to my highest self.",
  "I choose to see the light that I am to this world.",
  "I am happy in my own skin and in my own circumstances.",
  "I see myself as a gift to my community.",
  "I am more than good enough and I get better every day.",
  "I give up the habit to criticize myself.",
  "I adopt the mindset to praise myself.",
  "I see the perfection in all my flaws and all my genius.",
  "I am a good person at all times of day and night.",
  "Giving up is easy and always an option so let's delay it for another day.",
  "I press on because I believe in my path.",
  "The past has no power over me anymore.",
  "I embrace the rhythm and the flowing of my own heart.",
  "I am deeply fulfilled with who I am.",
  "My actions  create constant prosperity.",
  "I am loved, loving, and lovable.",
  "I believe I can be all that I want to be.",
  "I choose to be kind to myself and love myself unconditionally.",
  "My possibilities are endless.",
  "I am worthy of my dreams.",
  "I am enough.",
  "Rejoice and love yourself today, 'cause baby, you were born this way.",
  "Good things are happening.",
  "Categorize me, I defy every label.",
  "You can take my wings but I'm still gonna fly.",
  "Even if it makes others uncomfortable, I will love who I am.",
  "I deserve to be loved as I am.",
  "I am intelligent.",
  "I am attractive.",
  "I am my own soulmate.",
  "I radiate confidence and others respect me.",
  "Happiness is my birthright.",
  "I awaken in the morning feeling happy and enthusiastic about life.",
  "I can tap into a wellspring of inner happiness anytime I wish.",
  "By allowing myself to be happy, I inspire others to be happy too.",
  "I have fun with all of my endeavors, even the most mundane.",
  "I find joy and pleasure in the most simple things in life.",
  "I attract positive, confident people.",
  "Life is happening in this moment.",
  "I observe my emotions without getting attached to them.",
  "I sow the seeds of peace wherever I go.",
  "I am fully present in all of my relationships.",
  "Calmness washes over me with every deep breath I take.",
  "Being calm and relaxed energizes my whole being.",
  "All the muscles in my body are releasing and relaxing.",
  "I transcend stress of any kind. I live in peace.",
  "I gently and easily return to the present moment.",
  "My compassion replaces anger with love.",
  "My potential to succeed is infinite.",
  "I speak kindly of others.",
  "I am significant.",
  "I am bold and courageous.",
  "I face difficulty with courage.",
  "I am full of vitality.",
  "There is always another way.",
  "There is always a solution to my problems.",
  "I am a kind and unique person.",
  "I make responsible decisions and consider how they affect other people.",
  "I feel relaxed and comfortable around other people.",
  "I am easy to talk to and I am confident when I am with others.",
  "I am excited about the amazing people I'm meeting today.",
  "I help others to accomplish their dreams.",
  "I have all the support and help I need.",
  "I have compassion when others don't understand my dreams.",
  "I am pursuing my own definition of success.",
  "I face every mountain with a smile and courage.",
  "My heart is calm.",
  "Everything is meant to be.",
  "I choose love, not fear.",
  "All that I seek is already within me.",
  "All is well in my world.",
  "As I forgive myself it becomes easier to forgive others.",
  "I am helpful.",
  "Life is powerful.",
  "We can be so desperate for love that we forget where we can always find it; within.",
  "It is never too late to be what you might have been.",
  "I will not ignore my own potential.",
  "I am a winner.",
  "I am fearless.",
  "I use my failures as stepping stones.",
  "I am the perfect age today.",
  "I adore my curves.",
  "I am sexy and attractive just as I am.",
  "I am a strong woman.",
  "I am romantic and passionate.",
  "I embrace my sexual self.",
  "My genitals do not define my gender.",
  "My feelings are valid.",
  "Your lives matter. Your voices matter. Your stories matter.",
  "The tools I need for success are in my possession.",
  "I have faith in my social skills.",
  "I'm in awe of what my body is capable of.",
  "I was not made to give up.",
  "I am who I want to be.",
  "I know my worth.",
  "I inspire others.",
  'I have the courage to say "no."',
  "I accept myself unconditionally.",
  "I am a beautiful person.",
  "We are all stronger, smarter, talented, beautiful, and more resilient than we were told.",
  "Once you've done something that you used to think was impossible, what could ever really scare you again?",
  "No person is your friend who demands your silence, or denies your right to grow.",
  "The most important day of your life is the day you decide you are good enough.",
  "I believe in me.",
  "I am creating my life exactly as I want it.",
  "I know what I am doing.",
  "I am amazing at channeling confidence.",
  "I am on the best path for me.",
  "I will achieve my goals.",
  "I am focused, persistent, and will never quit.",
  "I only set goals that matter.",
  "My focus on success is unwavering.",
  "I will master distractions and focus on my goals.",
  "I will search for the good that comes, even in bad situations.",
  "I am constantly improving.",
  "Where others see a challenge, I see new opportunities.",
  "I have a growth mindset.",
  "Mindfulness helps me get the most from my time.",
  "I follow my dreams with vigor.",
  "The little things in life make all the difference.",
  "My challenges bring me better opportunities.",
  "My negative thoughts and self-images are gone.",
  "My life is an adventure.",
  "I give myself permission to slow down.",
  "I will take time to put myself first.",
  "I will act after thought, not on instinct.",
  "I see myself in my ideal job.",
  "I will work smarter, not harder.",
  "I'm energized and ready to slay the day.",
  "Positive energy surrounds me.",
  "I am worth it.",
  "I control my day; I will not let my day control me.",
  "My only limit is myself.",
  "My success is inevitable.",
  "I am my own superhero.",
  "My presence is my power.",
  "Am I good enough? Yes I am.",
  "Who you are inside is what helps you make and do everything in life.",
  "Good riddance to decisions that don't support self-care, self-value, and self-worth.",
  "I am deliberate and afraid of nothing.",
  "Your perspective is unique. It's important and it counts.",
  "Nothing can dim the light that shines from within.",
  "Gratitude is a celebration we are all invited to.",
  'Nothing is impossible. The word itself says "I\'m possible!"',
  "Failure is just another way to learn how to do something right.",
  "Everything passes if you learn to hold things lightly.",
  "Change the world by being yourself.",
  "Whatever you do, do it well.",
  "When you can't find the sunshine, be the sunshine.",
  "Wherever life plants you, bloom with grace.",
  "When life hands you a difficult situation where you feel undervalued and disrespected, be bold and brave enough to know your worth.",
  "Nothing will stop me from succeeding.",
  "Today is a beautiful day.",
  "My mind is filled with happy thoughts.",
  "I am empowered.",
  "I am happy to be alive.",
  "No matter what happens today, I will stay positive and upbeat.",
  "I am accomplishing great things.",
  "I am a magnet for abundance and success.",
  "I can turn any negative situation into a positive one.",
  "Every day I am getting better at what I do.",
  "I am creative.",
  "My authentic self is of immense value to the world.",
  "I have a great deal of respect for myself.",
  "Don't let your fear of what could happen make nothing happen.",
  "The pain you feel today will be the strength you feel tomorrow.",
  "I will be fearless.",
  "I can handle anything life throws at me.",
  "It's okay to cry. Sadness is part of life and everyone experiences it.",
  "I have strong willpower.",
  "My mind is clear and sharp.",
  "I am grounded.",
  "Creativity flows naturally into all of my endeavors.",
  "Inspiration comes naturally to me.",
  "I have a wealth of good ideas.",
  "I let go of any fears of rejection.",
  "My partnership is becoming stronger, deeper, and more stable each day.",
  "I want the best for my partner and I support them.",
  "My partner and I have a deep understanding.",
  "I get to choose what family means to me.",
  "The perfect partner for me is coming into my life sooner than I expect.",
  "Each day, I am closer to finding the perfect job for me.",
  "My business is growing, expending, and thriving.",
  "Through TWC, I feel empowered and connected  to other trans women.",
  "Today is a great day for self-care!",
  "Journaling brings clarity to your experiences.",
  "Today is a good day to review your vision board!",
  "Others' experiences are valuable -- check out mentorship opportunities!",
  "Reflect upon others' experiences to inform your own -- check out mentorship opportunities!",
  "Resources are abundant -- check out the resource map.",
  "Serendipity is everywhere. Check out the forums for unexpected answers to your questions.",
  "My gender experience is unique, just like me.",
  "Make using condoms easy, great job remembering to squeeze the tip!",
  "Your boundaries are radiant with your confidence.",
  "Thinking about your decisions helps you honor your truth and express your beauty.",
  "Your trembling voice is not a sign of weakness, it is a sign of strength for you to assert your request.",
  "Your chocolate box grants you the tastiest sex you desire. Communicate a sample with your partner.",
  "HIV and STI testing empowers you to keep you and your community healthy.",
  "My relationship bouquet empowers me to seek and create healthy relationships.",
  "Misrecognition may happen to me but it does not define me.",
];
/*
///////////////////////////////////////////////////////////////////////////////////
__          __ _     _____  _   _ _____ _   _  _____ 
\ \        / // \   |  __ \| \ | |_   _| \ | |/ ____|
 \ \  /\  / // . \  | |__) |  \| | | | |  \| | |  __ 
	\ \/  \/ // /_\ \ |  _  /| . ` | | | | . ` | | |_ |
	 \  /\  // _____ \| | \ \| |\  |_| |_| |\  | |__| |
	  \/  \//_/     \_\_|  \_\_| \_|_____|_| \_|\_____|
///////////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////////
EDITING BELOW THIS LINE MAY AFFECT CORE FUNCTIONALITY							 
///////////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////////
*/

/**
 * LOADING SCREEN TRANSITION
 * Transition to the main user page after some seconds
 */
const delay = 5;
const originName = "/TWC/";

if (
  window.location.pathname == "/index.html" ||
  window.location.pathname == originName
) {
  /**
   * LOADING SCREEN QUOTE GENERATOR
   * Loads a random quote at the bottom of loading screen
   */
  const footer = document.querySelector("#loadingQuote");
  const quoteElement = document.createElement("p");
  quoteElement.innerHTML =
    loadingQuotes[Math.floor(Math.random() * loadingQuotes.length)];

  footer.append(quoteElement);

  let timer = 0;

  setInterval(() => {
    console.log(timer);
    timer++;
    if (timer === delay) {
      window.location.replace("./Pages/users.html");
    }
  }, 1000);
}
